version: "3.9"

services:
  manager:
    build: ./manager
    ports:
      - "8080:8080"
    environment:
      - WORKER_URLS=http://worker:8000
    networks:
      - crackhash_net

  worker:
    build: ./worker
    networks:
      - crackhash_net

networks:
  crackhash_net:
    driver: bridge